openweather.apiKey=c5a428161544cd43b745718783f17270
gemini.api.key=AIzaSyAxglHGoiVKMTbH5mQMD50ntO9iDcuXFOU
currency.api.key=cur_1ive_E2Sp0e69Pw117cwYHkb06IFxZ3QJm3jVmI21khrxk
openai.api.key=YOUR_API_KEY
